server:
  port: 80


cowin:
  ddmm: 07-05
  district: 294
  api:
    auth-base: https://cdn-api.co-vin.in/api/v2/auth/public
    appointment-base: https://cdn-api.co-vin.in/api/v2/appointment/sessions/public